function FOL_TTM_VirtPageview(category,agof) { /*nn*/}
                        var utag_data={"brand": "focus",
                                          "pageCanonicalUrl": "https://www.focus.de/politik/ausland/nach-dem-tod-von-jewgeni-prigoschins-sohn-soll-wagner-fuehrung-uebernehmen-mit-25-jahren_id_217022535.html",
                                          "pageCanonicalUrlHash": "98aa414fb72e8948ab73dd1bbb0021aa",
                                          "pageContentId": "esc-217022535",
                                          "pageContentPlattformId": "b5bd05fd-017a-58e5-85e4-bb0afd8e35bf",
                                          "environment": "prod",
                                          "platform": "web",
                                          "appId": "focus_web-prod",
                                          "pageDisplayFormat": "desktop",
                                          "pageLevel1": "politik",
                                          "pageLevel2":"ausland","pageLevel3":"n/a",
                                          "pageTemplate": "videoarticle",
                                          "pageTemplateDetail": "videoarticle",
                                          "pageIvwCode": [typeof tft_ivw_match !== "undefined" ? tft_ivw_match : "","n/a"],
                                          "pageIvwOfferIdentifier": ["focus","n/a"],
                                          "pagePublishDateTimeUtc": "2023-10-02T10:46:08+00:00",
                                          "pageUpdateDateTimeUtc": "2023-10-03T08:29:46+00:00",
                                          "pageAuthor": ["Julian  Schmucker"],
                                          "pageAdKeyword": ["fol_ausland","fol_politik","fol_politik_ausland"],
                                          "pageviewRevenueId": document.querySelector('meta[property="bf:id_pi"]') ? document.querySelector('meta[property="bf:id_pi"]').getAttribute("content") : 'n/a',
                                          "salesforcePartnerId": "P0000",
                                          "salesforceDataproviderId": "D0000",
                                          "pageJob": "news-to-be-smart",
                                          "pageJobId": "0004",
                                          "pageInitialPageTitle": "Prigoschin-Sohn Pawel: Das ist der Mann, der jetzt Wagner übernehmen soll – er ist erst 25 Jahre alt",
                                          "pageCurrentPageTitle": "Prigoschin-Sohn Pawel: Das ist der Mann, der Wagner-Söldner führen soll – er ist erst 25 Jahre alt",
                                          "pageName": "esc-217022535 | Prigoschin-Sohn Pawel: Das ist der Mann, der jetzt Wagner übernehmen soll – er ist erst 25 Jahre alt",
                                          "pageEscenicId": "217022535",
                                          "dataLayerVersion": "1.0.0"};