!function(a,b){"object"==typeof exports&&"undefined"!=typeof module?b(exports):"function"==typeof define&&define.amd?define(["exports"],b):b((a="undefined"!=typeof globalThis?globalThis:a||self).idb={})}(this,function(a){function b(h){return h!==IDBDatabase.prototype.transaction||"objectStoreNames"in IDBTransaction.prototype?(g||=[IDBCursor.prototype.advance,IDBCursor.prototype.continue,IDBCursor.prototype.continuePrimaryKey]).includes(h)?function(...k){return h.apply(y.get(this),k),e(m.get(this))}:
function(...k){return e(h.apply(y.get(this),k))}:function(k,...l){l=h.call(y.get(this),k,...l);return r.set(l,k.sort?k.sort():[k]),e(l)}}function d(h){return"function"==typeof h?b(h):(h instanceof IDBTransaction&&function(l){if(!n.has(l)){var u=new Promise((t,v)=>{const q=()=>{l.removeEventListener("complete",p);l.removeEventListener("error",w);l.removeEventListener("abort",w)},p=()=>{t();q()},w=()=>{v(l.error||new DOMException("AbortError","AbortError"));q()};l.addEventListener("complete",p);l.addEventListener("error",
w);l.addEventListener("abort",w)});n.set(l,u)}}(h),k=h,(c||=[IDBDatabase,IDBObjectStore,IDBIndex,IDBCursor,IDBTransaction]).some(l=>k instanceof l)?new Proxy(h,A):h);var k}function e(h){if(h instanceof IDBRequest)return function(l){const u=new Promise((t,v)=>{const q=()=>{l.removeEventListener("success",p);l.removeEventListener("error",w)},p=()=>{t(e(l.result));q()},w=()=>{v(l.error);q()};l.addEventListener("success",p);l.addEventListener("error",w)});return u.then(t=>{t instanceof IDBCursor&&m.set(t,
l)}).catch(()=>{}),y.set(u,l),u}(h);if(z.has(h))return z.get(h);const k=d(h);return k!==h&&(z.set(h,k),y.set(k,h)),k}function f(h,k){if(h instanceof IDBDatabase&&!(k in h)&&"string"==typeof k){if(B.get(k))return B.get(k);var l=k.replace(/FromIndex$/,""),u=k!==l,t=C.includes(l);if(l in(u?IDBIndex:IDBObjectStore).prototype&&(t||D.includes(l)))return h=async function(v,...q){v=this.transaction(v,t?"readwrite":"readonly");let p=v.store;return u&&(p=p.index(q.shift())),(await Promise.all([p[l](...q),t&&
v.done]))[0]},B.set(k,h),h}}let c,g;const m=new WeakMap,n=new WeakMap,r=new WeakMap,z=new WeakMap,y=new WeakMap;let A={get(h,k,l){if(h instanceof IDBTransaction){if("done"===k)return n.get(h);if("objectStoreNames"===k)return h.objectStoreNames||r.get(h);if("store"===k)return l.objectStoreNames[1]?void 0:l.objectStore(l.objectStoreNames[0])}return e(h[k])},set:(h,k,l)=>(h[k]=l,!0),has:(h,k)=>h instanceof IDBTransaction&&("done"===k||"store"===k)||k in h};const D=["get","getKey","getAll","getAllKeys",
"count"],C=["put","add","delete","clear"],B=new Map;A=(h=>({...h,get:(k,l,u)=>f(k,l)||h.get(k,l,u),has:(k,l)=>!!f(k,l)||h.has(k,l)}))(A);a.deleteDB=function(h,{blocked:k}={}){h=indexedDB.deleteDatabase(h);return k&&h.addEventListener("blocked",()=>k()),e(h).then(()=>{})};a.openDB=function(h,k,{blocked:l,upgrade:u,blocking:t,terminated:v}={}){const q=indexedDB.open(h,k);h=e(q);return u&&q.addEventListener("upgradeneeded",p=>{u(e(q.result),p.oldVersion,p.newVersion,e(q.transaction))}),l&&q.addEventListener("blocked",
()=>l()),h.then(p=>{v&&p.addEventListener("close",()=>v());t&&p.addEventListener("versionchange",()=>t())}).catch(()=>{}),h};a.unwrap=h=>y.get(h);a.wrap=e});function numberWithCommas(a){return parseInt(a).toString().replace(/\B(?=(\d{3})+(?!\d))/g,",")}function escapeHTML(a){return $("<div/>").text(a).html()}function titleize(a){return a.charAt(0).toUpperCase()+a.slice(1)}function extractTS(a){return parseInt(1E3*parseFloat(a))}function isIE(){return/MSIE (\d+\.\d+);/.test(navigator.userAgent)}
function log(a){console.log(a)}function pageHidden(){return document.hidden||document.msHidden||document.webkitHidden||document.mozHidden}function validateEmail(a){return/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(a)}
function parseDate(a){var b=a.split(/ /);x=Date.parse(b[1]+" "+b[2]+", "+b[5]+" "+b[3]+" UTC");isNaN(x)&&(x=Date.parse(b[0]+"T"+b[1]));isNaN(x)&&(x=Date.parse(a));return res=new Date(x)}function getDateFromEpochString(a){var b=new Date;if(!a||""==a)return b;a=parseInt(a);if(0>=a)return b;b.setTime(1E3*a);return b}function clone(a){if(null==a||"object"!=typeof a)return a;var b=a.constructor(),d;for(d in a)a.hasOwnProperty(d)&&(b[d]=a[d]);return b}
function hexToRgb(a){return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?{r:parseInt(a[1],16),g:parseInt(a[2],16),b:parseInt(a[3],16)}:null}function rgbToRgb(a){var b=/^rgba\((\d+)\s*,\s*(\d+),\s*(\d+)\s*,\s*([\d\.]+)/i.exec(a);return b?{r:parseInt(b[1]),g:parseInt(b[2]),b:parseInt(b[3]),a:parseFloat(b[4])}:(b=/^rgb\((\d+)\s*,\s*(\d+)\s*,\s*(\d+)/i.exec(a))?{r:parseInt(b[1]),g:parseInt(b[2]),b:parseInt(b[3])}:null}var urlParams;
(window.onpopstate=function(){var a,b=/\+/g,d=/([^&=]+)=?([^&]*)/g,e=window.location.search.substring(1);for(urlParams={};a=d.exec(e);)urlParams[decodeURIComponent(a[1].replace(b," "))]=decodeURIComponent(a[2].replace(b," "))})();function animatedTextReplace(a,b){a&&(a.animate({opacity:"0"},200),a.queue(function(){a.html(b);a.dequeue()}),a.animate({opacity:"1"},400))}function actionl(a,b){$.ajax({type:"POST",url:"/al?t="+a+"&c="+encodeURIComponent(b)});return!1}
function cliente(a){$.ajax({type:"POST",url:"/ce",data:a});return!1}function infol(a){$.ajax({type:"POST",url:"/ilg",data:a});return!1}function checkGAEvents(){var a=$.cookie("gae");a&&(a=a.split(":"),trackEvent(a[0],a[1],a[2],a[3],a[4],a[5]),$.cookie("gae",null,{path:"/"}));if(a=$.cookie("gap"))trackPageView(a),$.cookie("gap",null,{path:"/"})}function trackPageView(a){a={hitType:"pageview",page:a};"undefined"!=typeof ga&&ga("send",a)}
function trackEvent(a,b,d,e,f,c){"undefined"!=typeof ga&&ga("send","event",b,d,e,f,{nonInteraction:c})}var cityURLPrefix="/local/",topicURLPrefix="/topic/",clearSubmitModalOnLoad=!0;$(document).ready(function(){$(".submit-modal").hide();clearSubmitModalOnLoad&&(window.onpageshow=function(a){$(".submit-modal").hide()});$(document).on("click",".contact_email",showContactBox);$(document).on("click",".contact_email_simple",showContactBoxSimple);$("#contact_us_form").on("submit",contactUsSubmit);checkGAEvents()});
var modalTimestamp=null;function checkSubmitModal(){var a=!0,b=(new Date).getTime(),d=$(".submit-modal");if("none"==d.css("display"))console.log("[checkSubmitModal] - Cancel, not displayed"),a=!1;else if(modalTimestamp){var e=modalTimestamp-b;(a=1200>e)?console.log("[checkSubmitModal] - Check",modalTimestamp,b,e,a):(console.log("[checkSubmitModal] - Cancel, timeout"),d.hide())}else console.log("[checkSubmitModal] - Start",modalTimestamp,b,e);modalTimestamp=b;a&&setTimeout(checkSubmitModal,1E3)}
function showSubmitModal(a){a=$(".submit-modal");a.height($(document).height());var b=Math.max($(window).height()-a.outerHeight(),0)/2;a.css({top:b+$(window).scrollTop()});a.fadeIn(1E3);var d=this;if(-1<navigator.userAgent.indexOf("Safari")&&0>navigator.userAgent.indexOf("Chrome"))return checkSubmitModal(),setTimeout(function(){document.location=$(d).attr("href")},1E3),!1}
function contactUsSubmit(a){a=$("#contact_us_account")&&$("#contact_us_account").val()||"";var b=$.trim($("#contact_us_subject")&&$("#contact_us_subject").val()||""),d=$.trim($("#contact_us_message")&&$("#contact_us_message").val()||""),e=$.trim($("#contact_us_email")&&$("#contact_us_email").val()||"");return 2>=b.length||5>=d.length||""==e||!validateEmail(e)?(window.alert("Please enter a valid subject, message and email"),!1):""==a&&(a=$.trim($("#contact_us_name")&&$("#contact_us_name").val()),b=
$.trim($("#contact_us_organisation")&&$("#contact_us_organisation").val()),1>=a.length||1>=b.length)?(window.alert("Please enter a valid name and organisation"),!1):!0}
function contactBoxHTML(a,b){a="<div id='contact_box' style='left:"+a+"px;top:"+b+"px;'><div style='text-align:center;font-weight:bold;font-size:14px;margin-bottom:10px;'>Contact Info</div><div class='contact-entry'>Email : <a href='mailto:trendsmap@trendsmap.com'>trendsmap@trendsmap.com</a></div>";a+="<div class='contact-entry'>Blog : <a target='_blank' href='/blog'>Trendsmap Blog</a></div>";a+="<div class='contact-entry'>Twitter : <a target='_blank' rel='nofollow' href='http://twitter.com/trendsmap' title='View Trendsmap profile on Twitter.com'>@trendsmap</a> ";
a+="</div>";a+="<div class='contact-entry' style='text-align:right'><a id='contact_box_close' href='#'>Close</a></div>";return a+="</div>"}function showContactBox(){var a=$(this),b=a.position(),d=b.top+a.height()+4;b=b.left-a.width()+50;d=contactBoxHTML(b,d);a.after(d);$(document).on("click","#contact_box",function(){$("#contact_box").slideUp("fast",function(){$("#contact_box").remove()})});return!1}
function contactBoxSimpleHTML(a,b){a="<div id='contact_box_simple' style='left:"+a+"px;top:"+b+"px;'><div style='text-align:center;font-weight:bold;font-size:18px;margin-bottom:10px;'>Contact Info</div><div class='contact-entry'>Email : <a href='mailto:trendsmap@trendsmap.com'>trendsmap@trendsmap.com</a></div>";a+="<div class='contact-entry' style='text-align:right'><a id='contact_box_close' href='#'>Close</a></div>";return a+="</div>"}
function showContactBoxSimple(){var a=$(this),b=a.position(),d=b.top+a.height()+4;b=contactBoxSimpleHTML(b.left-0,d);a.after(b);$(document).on("click","#contact_box_simple",function(){$("#contact_box_simple").slideUp("fast",function(){$("#contact_box_simple").remove()})});return!1}var cityURLFilter=null;
function wordCity(a,b){var d=a[0].word&&a[0].word.wordTile.cities||null;if(d)for(var e=0;e<d.length;e++)if(d[e][0]==a[0].lat&&d[e][1]==a[0].lon){if(b){a=cityURLPrefix+d[e][2]+"/"+d[e][3].replace(" ","+");if(cityURLFilter){b=a;a="#";for(var f=0;f<cityURLFilter.length;f++)if(cityURLFilter[f]==b){a=b;break}}return[d[e][4],a]}return d[e][4]}return b?["","#"]:""}
function wordCity2(a,b){var d=a[0].word&&a[0].word.wordTile.cities||null;if(d)for(var e=0;e<d.length;e++){var f=d[e];if(f.lat==a[0].lat&&f.lon==a[0].lon){if(b){a=cityURLPrefix+f.country_code+"/"+f.slug;if(cityURLFilter)for(b=a,a="#",d=0;d<cityURLFilter.length;d++)if(cityURLFilter[d]==b){a=b;break}return[f.title,a]}return f.title}}return b?["","#"]:""}
function clearSparkline(a,b){$("#"+a).show();$("#"+a).html("<div class='sparkline-loading'>"+(b?"":"<i class='fa fa-circle-o-notch fa-spin'></i>")+"</div>")}
function updateSparkline(a,b,d,e,f){d||=1;e||=18;b=$("#"+b);for(var c=0,g=0;g<a.length;g++)a[a.length]>c&&(c=a[a.length]);b.sparkline(a,{type:"line",height:e,lineColor:"#888",fillColor:"#DDD",spotColor:"#FFF",chartRangeMin:0,chartRangeMax:c,spotRadius:0,defaultPixelsPerValue:d,lineWidth:1,disableInteraction:!0});f&&(a=b.children()[0])&&(a=a.getContext("2d"),a.fillStyle="rgba(0,0,255,0.2)",a.globalCompositeOperation="destination-over",a.fillRect(149-149*f/168,0,149,18))}
function linkify_user_entities(a){if(a.entities){var b=a.entities;b.url?(a.url_html="<a rel='nofollow' target='_blank' href='"+escapeHTML(b.url.urls[0].expanded_url)+"'>"+b.url.urls[0].display_url+"</a>",a.expanded_url=b.url.urls[0].expanded_url,a.display_url=b.url.urls[0].display_url):(a.url_html="",a.expanded_url="",a.display_url="");var d={};$.each(b.description.urls,function(n,r){d[r.indices[0]]=[r.indices[1],function(z){return"<a href='"+escapeHTML(r.url)+"'>"+escapeHTML(r.display_url)+"</a>"}]});
b="";var e=0,f=0,c=a.description;for(f=0;f<c.length;++f){var g=d[f];if(g){var m=g[0];g=g[1];f>e&&(b+=escapeHTML(c.substring(e,f)));b+=g(c.substring(f,m));f=m-1;e=m}}f>e&&(b+=escapeHTML(c.substring(e,f)));a.description=b}}
function linkify_entities(a){if(!a.entities)return escapeHTML(a.text);var b={};$.each(a.entities.urls,function(m,n){b[n.indices[0]]=[n.indices[1],function(r){return"<a title='"+escapeHTML(n.expanded_url)+"' href='"+escapeHTML(n.url)+"'>"+escapeHTML(n.display_url)+"</a>"}]});$.each(a.entities.hashtags,function(m,n){b[n.indices[0]]=[n.indices[1],function(r){return"<a title='Search for #"+n.text+" on twitter.com' href='http://twitter.com/search?q="+escape("#"+n.text)+"'>"+escapeHTML(r)+"</a>"}]});$.each(a.entities.user_mentions,
function(m,n){b[n.indices[0]]=[n.indices[1],function(r){return"<a title='View "+escapeHTML(n.name)+" (@"+n.screen_name+") on twitter.com' href='http://twitter.com/"+escapeHTML(n.screen_name)+"'>"+escapeHTML(r)+"</a>"}]});var d="",e=0,f=0;for(f=0;f<a.text.length;++f){var c=b[f];if(c){var g=c[0];c=c[1];f>e&&(d+=escapeHTML(a.text.substring(e,f)));d+=c(a.text.substring(f,g));f=g-1;e=g}}f>e&&(d+=escapeHTML(a.text.substring(e,f)));return d}
function getCityLocation(){if($.cookie("c")){var a=$.cookie("c").split(",");parseInt(a[0]);var b=parseFloat(a[1]);a=parseFloat(a[2]);b=[b,a,7,2]}else b=tmAccount&&tmAccount.getClientLocation();return b}
function getDefaultViewport(a){var b=[[],[]];b[0][0]="SouthAmerica";b[0][1]="SouthAmerica";b[0][2]="Africa";b[0][3]="AusPac";b[1][0]="NorthAmerica";b[1][1]="NorthAmerica";b[1][2]="Europe";b[1][3]="Asia";var d={Africa:[-20,25,4,0],AusPac:[-30,144,4,0],SouthAmerica:[-20,-65,4,0],Europe:[52,15,5,0],Asia:[15,90,4,0],NorthAmerica:[40,-100,4,0]};if(a)return d[a];var e=getCityLocation();a=parseInt((e[0]+90)/90);var f=parseInt((e[1]+180)/90);a=d[b[a][f]];a[3]=e[3];return a}
function tweetEmbedHTML(a){return'<div class="fotorama-tweet-container-list"><blockquote class="twitter-tweet" style="display:block" data-id="'+a+'" data-width="250" data-align:"center"><a href="https://twitter.com/twitter/status/'+a+'"></a></blockquote></div>'}
function setupGallery(a,b,d){for(var e=[],f=0;f<b.length;f++){var c=b[f],g=c.url&&c.url.match(/^https:\/\/twitter\.com\/[a-zA-Z0-9_]+\/status\/(\d+)/)||null;g=g&&g[1];if(c.id_str)g="https://twitter.com/"+c.from_user+"/status/"+c.id_str,c.html='<div class="fotorama-tweet-container"><blockquote class="twitter-tweet" style="display:block" data-width="550" data-align:"center"><a href="'+g+'"></a></blockquote></div>',c.caption=null,c.img=null,c.thumb="/tdata/c/users/profile_image/"+c.from_user+"?size=reasonably_small";
else if(g)c.html="<div style='width:100%;text-align:center'><img style='width:16px;height:16px;margin:0 auto;margin-top:50px;' src='/images/spinner.gif'></div>",c.id_str=g,c.from_user=c.from_user||c.url.split("/")[3],c.caption=null,c.img=null,c.thumb="/tdata/c/users/profile_image/"+c.from_user+"?size=reasonably_small",c.caption=null,c.title=null;else if(c.screen_name){g="https://twitter.com/"+c.screen_name;var m="/tdata/c/users/profile_image/"+c.screen_name+"?size=original";c.thumb="/tdata/c/users/profile_image/"+
c.screen_name+"?size=reasonably_small";c.html='<div class="fotorama-account-container"><div class="account-details-wrap"><div class="account-col-img"><div class="tweet-image-wrap"><a class="tweet_image_link" title="'+c.name.replace("'","")+'" target="_new" href="'+g+'"><img onerror="this.parentNode.parentNode.style.display="none"" alt="@'+c.screen_name+'" class="tweet_image" src="'+m+'"/></a></div></div><div class="tweet-account-description"><a class="tweet_image_link" title="'+c.name.replace("'",
"")+'" target="_new" href="'+g+'">'+c.name+"</a></br><small>Following: "+c.friends_count+", Followers: "+c.followers_count+"</small><br/>"+c.description+"</br><i>"+c.location+'</i></div><div class="inline-url-domain-wrap"><div class="inline-url-domain"><i class="fa fa-twitter inline-tweet-icon"></i> <a target="_blank" href="'+g+'">@'+c.screen_name+'</div></div></div><div class="account-tweet-list">';g=Math.min(10,c.tweets.length);for(m=0;m<g;m++)c.html+=tweetEmbedHTML(c.tweets[m][0]);c.html+="</div></div>"}else if("https://vine.co/v/"==
c.url.slice(0,18))g=c.url+"/embed/postcard",c.html='<div class="vine-container-wrap"><div class="vine-container"><iframe src="'+g+'" frameborder="0"></iframe></div></div>',c.img=null,c.caption=null;else if("https://twitter.com/"==c.url.slice(0,20))g=c.url.split("/").slice(0,6).join("/"),c.html='<div class="fotorama-tweet-container"><blockquote class="twitter-tweet" style="display:block" data-width="550" data-align:"center"><a href="'+g+'"></a></blockquote></div>',c.caption=null,c.img=null,c.thumb||
(c.thumb=c.thumbnail_url);else{if(c.media_url){if(c.img=c.media_url,g=c.url.split("/")[2],c.thumb="https://www.google.com/s2/favicons?domain="+g,c.html='<div class="fotorama-url2-container"><a target="_blank"  href="'+c.url+'"><img onerror="galleryScreenshotLoadError(this);" class="fotorama-url-screenshot" src="'+c.img+'"></a>',c.html+='<div class="fotorama-url-title"><a target="_blank"  href="'+c.url+'">'+(c.title||c.caption)+"</a></div>",c.description||c.media_caption)c.html+="<div class='fotorama-gallery-image-description'>"+
(c.description||c.media_caption)+"</div>"}else c.img="/url_screenshot?url="+encodeURIComponent(c.url),g=c.url.split("/")[2],c.thumb="https://www.google.com/s2/favicons?domain="+g,c.html='<div class="fotorama-url-container"><a target="_blank"  href="'+c.url+'"><img onerror="galleryScreenshotLoadError(this);" class="fotorama-url-screenshot" src="'+c.img+'"></a>',c.html+='<div class="fotorama-url-title"><a target="_blank"  href="'+c.url+'">'+(c.title||c.caption)+"</a></div>";c.html+='<div class="fotorama-url-domain"><img src="'+
c.thumb+'"> '+g+"</div>";c.html+="</div>";e[e.length]=c.html;c.img=null;c.caption=null;c.title=null}}d=d||{};d.linkSelector=a;0<e.length&&(d.cacheHTML="<div class='image-cache-div'>"+e.join("")+"</div>");return new FotoramaPopup(d,b)}
function setupTweetGallery(a,b,d){if(b&&0!=b.length){for(var e=[],f=0;f<b.length;f++){var c=b[f];c.html="<div style='width:100%;text-align:center'><img style='width:16px;height:16px;margin:0 auto;margin-top:50px;' src='/images/spinner.gif'></div>";c.id_str=c.id_str||c.url&&c.url.split("/")[5];c.from_user=c.from_user||c.user&&c.user.screen_name||c.url.split("/")[3];c.thumb=c.user&&c.user.profile_image_url_https&&c.user.profile_image_url_https.replace("_normal.","_reasonably_small.")||"/tdata/c/users/profile_image/"+
c.from_user+"?size=reasonably_small";c.caption=c.img=c.caption=c.title=null}d=d||{};d.type="embed_tweet";d.linkSelector=a;0<e.length&&(d.cacheHTML="<div class='image-cache-div'>"+e.join("")+"</div>");return new FotoramaPopup(d,b)}}function galleryScreenshotLoadError(a){$(a).hide()}
function setupSearch(){$(".top-search-icon").click(showSearchForm);$("#search_submit").click(updateSearchResults);$("#search").submit(updateSearchResults);$("#search").keyup(checkUpdateSearchResults);$("#custom_search_close").click(showSearchForm)}var searchFormOpen=!1;function showSearchForm(a){var b=$("#custom_search");searchFormOpen?b.hide():($(a.currentTarget).offset(),b.css("left","auto"),b.css("right","20px"),b.show(),$("#search_query").focus());searchFormOpen=!searchFormOpen}
function checkUpdateSearchResults(){var a=$("#search_query");clearTimeout(a[0].timer);var b=a.val();3>b.length?closeSearchResults():a[0].previousQ!=b&&(a[0].timer=setTimeout(function(){updateSearchResults(null,!0)},700))}function closeSearchResults(){$("#dropdown").slideUp("normal")}
function updateSearchResults(a,b){a=$("#search_query");clearTimeout(a[0].timer);var d=a.val();d==a[0].previousQ&&"none"!=$("#dropdown").css("display")?b||$("#dropdown").slideUp("normal"):($("#topic_search_results").html("Loading..."),$("#analytics_search_results").html("Loading..."),$("#location_search_results").html("Loading..."),$("#user_search_results").html("Loading..."),$("#dropdown").slideDown("normal"),$.getJSON("/search?q="+encodeURIComponent(d),loadSearchResults),a[0].previousQ=d);return!1}
function loadSearchResults(a){var b=$("#topic_search_results"),d=$("#analytics_search_results"),e=$("#location_search_results"),f=$("#user_search_results");if(a&&a.l&&0<a.l.length){for(var c=["<ul>"],g=0;g<a.l.length;g++){var m=a.l[g][0];c[c.length]="<li><a class='location_search' href='"+cityURLPrefix+a.l[g][1]+"' title='"+m+"'>"+m+"</a></li>"}c[c.length]=["</ul>"];e.html(c.join("\n"))}else e.html("<ul><li>No Locations Found</li></ul>");e=$("#search_query").val();g="<li><a class='topic_search analytics-search' href='/analytics?hours=24&extract_urls=1&q="+
encodeURIComponent(e)+"' title='"+e+"'>"+e+"</a></li></ul>";if(a&&a.t&&0<a.t.length){c=["<ul>"];var n=["<ul>"];n[n.length]=g;for(g=0;g<a.t.length;g++)m=a.t[g][0],c[c.length]="<li><a class='topic_search' href='"+topicURLPrefix+encodeURIComponent(m)+"' title='"+m+"'>"+m+"</a></li>",m!=e&&(n[n.length]="<li><a class='topic_search analytics-search' href='/analytics?hours=24&extract_urls=1&q="+encodeURIComponent(m)+"' title='"+m+"'>"+m+"</a></li>");c[c.length]=["</ul>"];c[n.length]=["</ul>"];b.html(c.join("\n"));
d.html(n.join("\n"))}else b.html(""),d.html("<ul>"+g+"</ul>");if(a&&a.u&&0<a.u.length){c=["<ul>"];for(g=0;g<a.u.length;g++)b=a.u[g],d=b[0],m=b[1],e="<span>"+numberWithCommas(b[2])+" Followers, "+numberWithCommas(b[3])+" Friends",b[4]&&(e+=" <span field='verified' class='user-details-verified' style='display: inline'><img src='/images/twitter_verified_14.png'></span>"),e+="</span>",c[c.length]="<li><a class='user_search' href='/twitter/user/"+m.toLowerCase()+"' title='See detailed activity analytics for "+
d+"'><i class='fa fa-user-o' aria-hidden='true'></i> @"+m+" - "+d+"</a> "+e+"</li>";c[c.length]=["</ul>"];f.html(c.join("\n"))}else f.html("");$(".analytics-search").on("click",function(r){$("#submit_modal_spinner");showSubmitModal();return!0})}function setupAnalyticsLinks(){$(".analytics-link").on("click",function(a){$("#submit_modal_spinner");showSubmitModal();return!0})}
function setupSpinnerLinks(){$(".spinner-link").on("click",function(a){$("#submit_modal_spinner");showSubmitModal();return!0})}function setupLazyLoad(a){if("undefined"!=typeof $.Lazy){var b={visibleOnly:!0,scrollDirection:"vertical",appendScroll:a};$("img.lazy").Lazy(b);setTimeout(function(){$("img.lazy").Lazy(b)},5E3);b.onError=function(d){d[0].parentNode.style.display="none"};$("img.lazy-lp").Lazy(b);setTimeout(function(){$("img.lazy-lp").Lazy(b)},5E3)}}
var Layout={settings:{autoScrollWhenMenuIsActive:!1,improvePerformance:!0,themeClass:"indigo"},handleThemeColor:function(){$body=$("body");$body.removeClass(function(a,b){return(b.match(/(^|\s)theme-\S+/g)||[]).join(" ")}).addClass("theme-"+this.settings.themeClass)},initLayer:function(){var a=$(window).height(),b=$(window).width(),d=$(".starting-point");a=2*Math.sqrt(Math.pow(a,2)+Math.pow(b,2));d.children("span").velocity({scaleX:0,scaleY:0,translateZ:0},50).velocity({height:a+"px",width:a+"px",
top:-(a/2)+"px",left:-(a/2)+"px"},0)},layerResponsive:function(){var a=$(window).height(),b=$(window).width(),d=$(".starting-point");a=2*Math.sqrt(Math.pow(a,2)+Math.pow(b,2));d.children("span").css({height:a+"px",width:a+"px",top:-(a/2)+"px",left:-(a/2)+"px"})},listenForSearchLayer:function(){$(".nav-search").on("click",function(){var a=$(".search-layer");a.hasClass("active")?(a.removeClass("active"),a.hide()):(a.addClass("active"),a.show(250,function(){Pleasure.checkTouchScreen()||a.find("input").focus()}))})},
listenKeyboardEvents:function(){$(document).keyup(function(a){var b=$(".nav-search"),d=$(".nav-menu");27==a.keyCode&&d.hasClass("active")&&d.trigger("click");27==a.keyCode&&b.hasClass("active")&&b.trigger("click")})},listenForMenuLayer:function(){$(".nav-menu").on("click",function(){var a=$(this),b=$(".starting-point"),d=$(".overlay"),e=$(".menu-layer"),f=$(".overlay-secondary"),c=$(".content"),g=$("body"),m=$(".scrollable-tabs"),n=$(".nav-search");$(".search-layer").hasClass("active")&&n.trigger("click");
e.find('[data-open-after="true"]').addClass("open");a.hasClass("active")?(a.addClass("rotating"),f.removeClass("fade-in"),c.removeClass("scaled"),setTimeout(function(){e.removeClass("active");$.Velocity.animate(b.children("span"),{translateZ:0,scaleX:0,scaleY:0},{duration:300,easing:[.42,0,.58,1],complete:function(){d.removeClass("active overlay-nav");a.removeClass("active rotating");e.removeClass("activating");g.removeClass("disable-scroll");e.find(".open").removeClass("open animate");m.removeClass("disabled")}})},
200)):(Pleasure.checkTouchScreen()||Layout.settings.improvePerformance||c.addClass("scaled"),e.addClass("activating"),m.addClass("disabled"),setTimeout(function(){g.addClass("disable-scroll");d.addClass("overlay-nav active");a.addClass("active");e.addClass("active");f.addClass("fade-in");e.find('[data-open-after="true"]').parents("li").addClass("open animate");$.Velocity.animate(b.children("span"),{translateZ:0,scaleX:1,scaleY:1},{duration:200,easing:[.42,0,.58,1]});Layout.settings.autoScrollWhenMenuIsActive&&
setTimeout(function(){e.velocity({scrollTop:e.find('[data-open-after="true"]').position().top+200},300)},600)},50))});$(".overlay-secondary").on("click",function(){$(".nav-menu").trigger("click")})},listenMenu:function(){$(".menu-layer a").on("click",function(){var a=$(this),b=$(this).parents(".menu-layer");a.parents("ul").hasClass("child-menu")?a.parent().hasClass("open")?a.parent().removeClass("open animate"):(a.parent().siblings(".has-child").removeClass("open animate"),a.parent().addClass("open"),
setTimeout(function(){a.parent().addClass("animate")},100)):a.parents("li").hasClass("open")?a.parents("li").removeClass("animate open"):(b.find(".open").removeClass("animate open"),a.parents("li").addClass("open"),setTimeout(function(){a.parents("li").addClass("animate")},10))});$(".menu-layer").find('li:has("ul")').each(function(){$(this).addClass("has-child")});$(".menu-layer").find("li").each(function(){$(this).append('<span class="hover-bg"></span>')})},handleSidebar:function(){var a=$(window),
b=$("body");767>=a.width()?b.addClass("layout-device layout-tablet"):767<a.width()&&990>a.width()?(b.addClass("layout-tablet"),b.removeClass("layout-device")):990<a.width()&&b.removeClass("layout-device layout-tablet")},init:function(){this.handleThemeColor();this.initLayer();Pleasure.callOnResize.push(this.layerResponsive);this.listenForMenuLayer();this.listenForSearchLayer();this.listenKeyboardEvents();this.listenMenu();this.handleSidebar();Pleasure.callOnResize.push(this.handleSidebar)}},latIP=
40,lonIP=-100,tmAccount,aca=null,aAction="view",aCategory="default",aGroup="explore",aWeight=0;$(document).ready(function(){tmAccount=new TMAccount;setupActivity("view")});
async function setupActivity(a){if(0!=aWeight&&"undefined"!=typeof lbp&&lbp){aca=new Activity;await aca.setup();aca.addA(aAction,aCategory,aWeight,aGroup);a=accessConfig||{};var b=await aca.checkA(a.a_group),d=a.aa||50;0<d&&b>d&&aGroup==a.a_group&&(a.li?(subscribeModalPro(!0),accessConfig&&accessConfig.li&&actionl("pro_limit",document.location.pathname+document.location.search)):(registerModal(!0),actionl("explore_limit",document.location.pathname+document.location.search)))}}
function TMAccount(){this.setup()}TMAccount.prototype={};TMAccount.prototype.setup=function(){this.checkHeaderMessages();accessConfig&&accessConfig.li&&actionl("page",document.location.pathname+document.location.search);this.setupHeader()};TMAccount.prototype.setupHeader=function(){accessConfig.li?($("#user_registered").show(),$("#user_registered_mobile").show()):($("#user_anonymous").show(),$("#user_anonymous_mobile").show())};
TMAccount.prototype.checkHeaderMessages=function(){"/twitter/tweet/"==document.location.pathname.slice(0,15)||accessConfig&&1==accessConfig.ccheck||$.cookie("ccheck")||urlParams.screenshot_mode||($("body").prepend("<div id='header_message' class='header-message'>By using this site, you agree to our use of cookies for performance, functionality and advertising. <a href='/privacy' style='font-size:12px;line:height:1.5'> Learn more </a> <button class='btn btn-primary'>OK</button></div>"),$("#header_message button").click(function(){$.cookie("ccheck",
1,{path:"/;SameSite=Strict",expires:365});$("#header_message").hide();accessConfig.li&&getRemoteMessage("ccheck",!1,function(){})}))};TMAccount.prototype.getClientLocation=function(){return[accessConfig.latIP||latIP,accessConfig.lonIP||lonIP,7,2]};function getClientLocation(){return tmAccount.getClientLocation()}var clientHeartbeatActive=!1,clientHeartbeatSequence=0,clientHeartbeatTimer;function setupClientHeartbeat(){clientHeartbeat();clientHeartbeatTimer=setInterval(clientHeartbeat,1E4)}
function stopHeartbeat(a){clearTimeout(clientHeartbeatTimer)}function restartHeartbeat(){clientHeartbeatActive=!1}
function processHeartbeat(a,b,d){if(a&&a.result&&"OK"==a.result){if("stop_hb"==a.action)stopHeartbeat(a);else if("logout"==a.action)logoutClient(a.message_id);else if("logout_multi"==a.action)logoutClientMultiUser(a.message_id);else if("message_modal"==a.action)clientMessageModal(a.message_id,a.message,a.block);else{if("redirect"==a.action){location.href=a.url;return}clientHeartbeatActive=!1}clientHeartbeatSequence+=1}else processFailedHeartbeat(d,b,a,!0)}
function processFailedHeartbeat(a,b,d,e){e&&doLogout();clientHeartbeatActive=!1}function clientHeartbeat(){clientHeartbeatActive||(clientHeartbeatActive=!0,$.ajax({type:"POST",url:"/hb",dataType:"json",data:{v:1,seq:clientHeartbeatSequence},success:processHeartbeat,error:processFailedHeartbeat}))}function logoutClient(a){$.cookie("fcelg",1,{path:"/"});var b=$("#multi_user_info").html();modal.open({content:b,hideClose:!1,onClose:function(){doLogout(a)}})}
function logoutClientMultiUser(a){modal.open({content:"This session has ended due to a newer session being created elsewhere with your login details",hideClose:!1,onClose:function(){doLogout(a)}})}function doLogout(a){$.cookie("logout",1,{path:"/"});a?markMessageAsRead(a,function(){window.location.href="/auth/destroy?return_to=/pricing"}):window.location.href="/auth/destroy?return_to=/auth"}function clientMessageModalOpen(a,b,d){d||markMessageAsRead(a)}
function clientMessageModalClose(a,b){markMessageAsRead(a);restartHeartbeat()}function getRemoteMessage(a,b,d){$.ajax({type:"GET",url:"/account/remote_message",dataType:"html",data:{v:1,message:a,block:b},success:d,error:function(){console.log("ERROR : Unable to get remote data for ",a)}})}
function clientMessageModal(a,b,d,e){if("#"==b[0]){var f=$(b).html();if(!f)return getRemoteMessage(b,d,function(c){clientMessageModal(a,c,d,e)}),!1;b=f}d&&($("#modal_overlay").css("z-index","99998"),$("#modal_modal").css("z-index","99999"));b&&""!=b?modal.open({content:b,hideClose:d,onOpen:function(){clientMessageModalOpen(a,b,d);e&&e()},onClose:function(){clientMessageModalClose(a,b)}}):console.log("ERROR : tried to display empty message for id=",a,", block=",d)}
function markMessageAsRead(a,b){-1!=a&&$.ajax({type:"POST",url:"/message_read",dataType:"json",data:{v:1,id:a},success:b,error:function(){console.log("Failed to mark off message ",a," as read")}})}function subscribeModal(a){clientMessageModal(-1,"#subscription_required",a,function(){$("#subscription_required").show()});return!1}function subscribeModalPro(a){clientMessageModal(-1,"#subscription_required_pro",a,function(){$("#subscription_required_pro").show()});return!1}
function registerModal(a){clientMessageModal(-1,"#register_login",a,function(){$("#register_login").show()});return!1}function Activity(){this.dbName="tm";this.tableName="activity";this.dbVersion=1;this.isSetup=!1}Activity.prototype.setup=async function(){const a=this.tableName;this.db=await idb.openDB(this.dbName,this.dbVersion,{upgrade(b){b.createObjectStore(a,{keyPath:"id",autoIncrement:!0}).createIndex("ms","ms")}});this.isSetup=!0;return this.db};
Activity.prototype.addA=async function(a,b,d,e){if(!this.isSetup)return!1;await this.add({href:document.location.href,action:a,category:b,aid:accessConfig&&accessConfig.aid||-1,group:e},d)};Activity.prototype.add=async function(a,b=1){await this.db.add(this.tableName,{ms:(new Date).getTime(),w:b,d:a})};Activity.prototype.del=async function(a){return await this.db.delete(this.tableName,a)};
Activity.prototype.checkA=async function(a){const b=(new Date).getTime(),d=await this.db.getAllFromIndex(this.tableName,"ms");let e=0;for(var f=0;f<d.length;f++){var c=d[f];const g=!a||c.d.group==a;24192E5>(b-c.ms)/1E3&&g?e+=c.w:this.del(c.id)}return e};
